version: 2
jobs:
  build:
    working_directory: ~/archon-fountainhead
    docker:
      - image: circleci/node:9.11.1

    steps:
      - checkout

      - run:
          name: Update NPM 
          command: |
            sudo npm install -g npm@latest
      
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run:
          name: Install dependencies
          command: npm install
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: Run unit tests
          command: |
            sudo npm install -g mocha
            npm test

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz \
              https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L -o /tmp/docker-compose \
              https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m`
            chmod +x /tmp/docker-compose
            sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run \
                --network container:app \
              appropriate/curl \
              http://localhost:3000/ \
                --retry 10 \
                --retry-delay 1 \
                --retry-connrefused
